-- All 50 seasons of the U.S. version of Survivor (through Survivor 50, spring 2026).
-- subtitle omits the "Survivor: " prefix; seasons 41-49 have no subtitle.
-- Source: en.wikipedia.org/wiki/Survivor_(American_TV_series)
INSERT INTO seasons (id, subtitle, wikipedia_url) VALUES
    (1,  'Borneo',                          'https://en.wikipedia.org/wiki/Survivor:_Borneo'),
    (2,  'The Australian Outback',          'https://en.wikipedia.org/wiki/Survivor:_The_Australian_Outback'),
    (3,  'Africa',                          'https://en.wikipedia.org/wiki/Survivor:_Africa'),
    (4,  'Marquesas',                       'https://en.wikipedia.org/wiki/Survivor:_Marquesas'),
    (5,  'Thailand',                        'https://en.wikipedia.org/wiki/Survivor:_Thailand'),
    (6,  'The Amazon',                      'https://en.wikipedia.org/wiki/Survivor:_The_Amazon'),
    (7,  'Pearl Islands',                   'https://en.wikipedia.org/wiki/Survivor:_Pearl_Islands'),
    (8,  'All-Stars',                       'https://en.wikipedia.org/wiki/Survivor:_All-Stars'),
    (9,  'Vanuatu',                         'https://en.wikipedia.org/wiki/Survivor:_Vanuatu'),
    (10, 'Palau',                           'https://en.wikipedia.org/wiki/Survivor:_Palau'),
    (11, 'Guatemala',                       'https://en.wikipedia.org/wiki/Survivor:_Guatemala'),
    (12, 'Panama',                          'https://en.wikipedia.org/wiki/Survivor:_Panama'),
    (13, 'Cook Islands',                    'https://en.wikipedia.org/wiki/Survivor:_Cook_Islands'),
    (14, 'Fiji',                            'https://en.wikipedia.org/wiki/Survivor:_Fiji'),
    (15, 'China',                           'https://en.wikipedia.org/wiki/Survivor:_China'),
    (16, 'Micronesia',                      'https://en.wikipedia.org/wiki/Survivor:_Micronesia'),
    (17, 'Gabon',                           'https://en.wikipedia.org/wiki/Survivor:_Gabon'),
    (18, 'Tocantins',                       'https://en.wikipedia.org/wiki/Survivor:_Tocantins'),
    (19, 'Samoa',                           'https://en.wikipedia.org/wiki/Survivor:_Samoa'),
    (20, 'Heroes vs. Villains',             'https://en.wikipedia.org/wiki/Survivor:_Heroes_vs._Villains'),
    (21, 'Nicaragua',                       'https://en.wikipedia.org/wiki/Survivor:_Nicaragua'),
    (22, 'Redemption Island',               'https://en.wikipedia.org/wiki/Survivor:_Redemption_Island'),
    (23, 'South Pacific',                   'https://en.wikipedia.org/wiki/Survivor:_South_Pacific'),
    (24, 'One World',                       'https://en.wikipedia.org/wiki/Survivor:_One_World'),
    (25, 'Philippines',                     'https://en.wikipedia.org/wiki/Survivor:_Philippines'),
    (26, 'Caramoan',                        'https://en.wikipedia.org/wiki/Survivor:_Caramoan'),
    (27, 'Blood vs. Water',                 'https://en.wikipedia.org/wiki/Survivor:_Blood_vs._Water'),
    (28, 'Cagayan',                         'https://en.wikipedia.org/wiki/Survivor:_Cagayan'),
    (29, 'San Juan del Sur',                'https://en.wikipedia.org/wiki/Survivor:_San_Juan_del_Sur'),
    (30, 'Worlds Apart',                    'https://en.wikipedia.org/wiki/Survivor:_Worlds_Apart'),
    (31, 'Cambodia',                        'https://en.wikipedia.org/wiki/Survivor:_Cambodia'),
    (32, 'Kaôh Rōng',                       'https://en.wikipedia.org/wiki/Survivor:_Kaôh_Rōng'),
    (33, 'Millennials vs. Gen X',           'https://en.wikipedia.org/wiki/Survivor:_Millennials_vs._Gen_X'),
    (34, 'Game Changers',                   'https://en.wikipedia.org/wiki/Survivor:_Game_Changers'),
    (35, 'Heroes vs. Healers vs. Hustlers', 'https://en.wikipedia.org/wiki/Survivor:_Heroes_vs._Healers_vs._Hustlers'),
    (36, 'Ghost Island',                    'https://en.wikipedia.org/wiki/Survivor:_Ghost_Island'),
    (37, 'David vs. Goliath',               'https://en.wikipedia.org/wiki/Survivor:_David_vs._Goliath'),
    (38, 'Edge of Extinction',              'https://en.wikipedia.org/wiki/Survivor:_Edge_of_Extinction'),
    (39, 'Island of the Idols',             'https://en.wikipedia.org/wiki/Survivor:_Island_of_the_Idols'),
    (40, 'Winners at War',                  'https://en.wikipedia.org/wiki/Survivor:_Winners_at_War'),
    (41, '',                                'https://en.wikipedia.org/wiki/Survivor_41'),
    (42, '',                                'https://en.wikipedia.org/wiki/Survivor_42'),
    (43, '',                                'https://en.wikipedia.org/wiki/Survivor_43'),
    (44, '',                                'https://en.wikipedia.org/wiki/Survivor_44'),
    (45, '',                                'https://en.wikipedia.org/wiki/Survivor_45'),
    (46, '',                                'https://en.wikipedia.org/wiki/Survivor_46'),
    (47, '',                                'https://en.wikipedia.org/wiki/Survivor_47'),
    (48, '',                                'https://en.wikipedia.org/wiki/Survivor_48'),
    (49, '',                                'https://en.wikipedia.org/wiki/Survivor_49'),
    (50, 'In the Hands of the Fans',        'https://en.wikipedia.org/wiki/Survivor_50');
